### ISSUE TITLE
[1.20.1 forge] crash on startup

### ISSUE THREAD

**Issue by PlayfulPiano** [unilock/EMI_loot#1]
[crash-2023-11-14_18.01.29-client.txt](https://github.com/unilock/EMI_loot/files/13358143/crash-2023-11-14_18.01.29-client.txt)
modlist below
- Just Enough Items [15.2.0.27]
- Ferrite Core [6.0.1]
- RyoamicLights [0.1.5+1.20.1]
- Corail Woodcutter [3.0.3]
- ME Requester [1.20.1-1.1.4]
- Iceberg [1.1.16]
- Enhanced Celestials [5.0.0.2]
- Paintings ++ [11.0.0.0]
- Specialised Cells [1.0.0]
- NetherPortalFix [13.0.0]
- Krypton Reforged [0.2.3]
- Pick Up Notifier [8.0.0]
- Rubidium/Embeddium Extra [0.5.3+mc1.20.1-build.106]
- Simple Storage Network [1.10.0]
- Xaero's Minimap [23.8.4]
- YUNG's Menu Tweaks [1.20.1-Forge-1.0.1]
- Enhanced Extinguishing [1.20.1-1.0.0-neoforge]
- VoidFog [1.20.1-2.0.23]
- Inventory Essentials [8.2.1]
- Smarter Farmers [1.20-1.7.3]
- Every Compat [1.20-2.6.16]
- Structory: Towers [1.0.5]
- Jump Over Fences [1.3.0]
- Just Enough Sculk Sensor [1.1.0]
- Cherished Worlds [6.1.4+1.20.1]
- Advancements Tracker [6.0.0]
- Cuisine Delight [1.1.10]
- XaeroPlus [1.20.1]
- SBM-Charcoal Block [1.1.0]
- DespawnTweaker [1.20.1-0.0.5]
- Lootintegrations mod [1.20.1-3.3]
- Illager Invasion [8.0.3]
- Smoothchunk mod [1.20.1-3.3]
- Alex's Mobs [1.22.6]
- Hearths [1.0.0-mc1.20u1.20.1]
- Just Enough Professions (JEP) [3.0.1]
- Applied Energistics 2 [15.0.15]
- Philips Ruins [2.5]
- Useful Railroads [1.5.6.56]
- Charm of Undying [6.4.5+1.20.1]
- FancyMenu [2.14.9]
- betterchunkloading mod [1.20.1-2.2]
- Memory Leak Fix [1.1.2]
- Inventory HUD+(Forge edition) [3.4.18]
- memorysettings mod [1.20.1-5.4]
- Underground Jungle [2.1-forge]
- Transparent [8.0.1+1.20.1]
- Repurposed Structures [7.1.11+1.20.1-forge]
- Wiki Lookup [1.0.2]
- AE2 QoL Recipes [1.1.1]
- Simple Discord Rich Presence [4.0.2-build.36+mc1.20.1]
- Moonlight Lib [RNUEccJ3]
- XP Tome [2.1.8]
- Highlight [2.0.1]
- Kiwi Library [11.1.1]
- Euphoria Patcher [0.1.1-forge]
- Alternate Current [1.7.0]
- Storage Drawers [12.0.2]
- VillagersPlus [3.0]
- Blue Skies [1.3.29]
- Visual Workbench [8.0.0]
- Cataclysm Mod [1.0]
- Neat [1.20-35-FORGE]
- Hearth & Home [1.20.1-2.0.1]
- Better Furnaces Reforged [1.1.1]
- Cloth Config v10 API [11.1.106]
- Right Click Harvest [3.2.3+1.20.1-forge]
- Ambient Environment [11.0.0.1]
- Sereneseasonfix [1.20.1-1.0.8]
- Comforts [6.3.4+1.20.1]
- Forge Config Screens [8.0.2]
- Advanced Netherite [2.0.2]
- EntityCulling [1.6.2]
- YUNG's Better Mineshafts [1.20-Forge-4.0.4]
- Vein Mining [1.2.1+1.20.1]
- Nyf's Archery Plus [1.1.0]
- CERBON's Better Beacons [1.0.2]
- RiverRedux [0.3.1]
- spark [1.10.53]
- Magnum Torch [8.0.0]
- Blossom Blade [1.0]
- DEUF - Duplicate Entity UUID Fix [1.20.1-1.3]
- Legendary Tooltips [1.4.5]
- YUNG's Better Dungeons [1.20-Forge-4.0.3]
- Replanting Crops [5.2]
- Responsive Shields [2.2]
- Traveler's Titles [1.20-Forge-4.0.1]
- Athena [3.1.1]
- Dungeons and Taverns [3.0.3]
- Waystones [14.0.2]
- Collective [7.7]
- Better Mods Button [8.0.2]
- Stack Refill [4.1]
- PingWheel [1.20.1-0.0.2]
- U Team Core [5.1.4.269]
- betterfpsdist mod [1.20.1-4.0]
- Raided [0.1.3]
- Rubidium Extras [1.20.1_v1.4.3]
- YUNG's Better Nether Fortresses [1.20-Forge-2.0.5]
- Cupboard utilities [1.20.1-2.1]
- libIPN [4.0.0]
- Sophisticated Backpacks [3.18.66.941]
- Gpu memory leak fix [1.20.1-1.6]
- CorgiLib [4.0.0.4]
- Patchouli [1.20.1-81-FORGE]
- Incendium [5.3.3]
- JustEnoughBeacons [1.1.1]
- Better Advancements [0.3.2.161]
- CIT Resewn [1.20.1-5]
- Blastin Raw Minerals [1.20.1-0-forge]
- Kotlin for Forge [zHr6G92U]
- Grass Overhaul [23.10.10]
- Polymorph [0.49.1+1.20.1]
- RevampedWolf [1.20.1-5.0.0]
- Mouse Tweaks [2.25]
- Oculus [1.6.9]
- Fastload-Reforged [3.4.0]
- ServerBrowser [1.0.0]
- Tips [12.0.4]
- Handcrafted [3.0.5]
- Wool Tweaks [3.2]
- Trading Post [8.0.1]
- Aether: Lost Content [1.2.2]
- Structure Essentials mod [1.20.1-3.1]
- Explorer's Compass [1.20.1-1.3.3-forge]
- Item Borders [1.2.0]
- MidnightLib [1.4.1]
- Structure Gel API [2.15.0]
- Caelus API [3.1.0+1.20]
- CullLeaves [3.2.0]
- Better Totem Of Undying [1.1.0]
- Elytra Slot [6.3.0+1.20.1]
- recipeessentials mod [1.20.1-3.1]
- Terralith Biome Saplings [1.0.9]
- YUNG's Better Witch Huts [1.20-Forge-3.0.3]
- Easy Shulker Boxes [8.0.0]
- YUNG's Better Ocean Monuments [1.20-Forge-3.0.3]
- AppleSkin [2.5.1+mc1.20.1]
- Visuality: Reforged [2.0.2]
- QuickStack [1.20.1-1]
- CraftingTweaks [18.2.1]
- Eating Animation [5.0.0]
- Architectury [9.1.12]
- Stoneworks [8.0.0]
- Durability Notifier [1.6.0]
- Guard Villagers [1.20.1-1.6.3]
- Resourceful Lib [2.1.16]
- Entity Texture Features [4.6.1]
- Chunk Loaders [1.2.8a]
- Goblin Traders [1.9.3]
- Puzzles Lib [8.1.8]
- Does Potato Tick [1.20.1-3.7.0]
- Catalogue [1.8.0]
- Advancement Plaques [1.4.10]
- Naturally Charged Creepers [3.3]
- SeasonHUD [1.5.13]
- ServerCore [1.3.9+1.20.1]
- Nether Chested [8.0.1]
- Softer Hay Bales [3.1]
- Urkaz Moon Tools [2.0.31]
- Searchables [1.0.2]
- chunksending mod [1.20.1-2.7]
- Snow Under Trees [1.4.2]
- Night Config Fixes [8.0.0]
- GeckoLib 4 [4.2.4]
- Borderless Window [1.20-1.6.0]
- Stalker Creepers [1.20.1.0]
- Dismount Entity [3.1]
- Better Compatibility Checker [4.0.8]
- CreativeCore [2.11.9]
- Geophilic [2.0.0-mc1.20u1.20.1]
- Portable Mobs [1.2.0]
- Sanity: Descent Into Madness [1.1.0]
- YUNG's API [1.20-Forge-4.0.2]
- HorseStatsMod [1.4.7]
- 3dSkinLayers [1.5.4]
- No Chat Reports [1.20.1-v2.2.2]
- Simple Magnets [1.1.10]
- EndlessBiomes [1.0.0]
- Chefs Delight [1.0.3-forge-1.20.1]
- Kambrik [6.1.1+1.20.1]
- KleeSlabs [15.0.0]
- Double Doors [5.1]
- The Aether: Redux [1.20.1]
- When Dungeons Arise [2.1.57-1.20.1]
- Yeetus Experimentus [2.3.1-build.6+mc1.20.1]
- Bygone Nether [1.3.2]
- clientcrafting mod [1.20.1-1.7]
- FullGrownCropMarker [1.20.1-1.2.0]
- Explorify [1.3.0-mc1.20]
- Another Furniture [1.20.1-3.0.1]
- Dragon Mounts: Legacy [1.1.5.b3]
- Umbral Skies [1.3]
- Villager Names [7.0]
- Friends&Foes [1.9.8]
- Fullblock Energistics [1.6-1.20.1]
- Konkrete [1.6.1]
- Scaffolding Drops Nearby [3.1]
- Controlling [12.0.2]
- Deep Aether [1.20.1-1.0.12]
- Easy Elytra Takeoff [4.1]
- Backpacked [2.2.5]
- Farsight mod [1.20.1-3.5]
- Item Filters [2001.1.0-build.59]
- Endorium [1.0.5]
- Quick Right-Click [1.2]
- Placeable Blaze Rods [3.2]
- BetterThanMending [1.7.2]
- FTB Teams [2001.1.4]
- Necronomicon [1.3.0]
- Resource Pack Overrides [8.0.2]
- YUNG's Bridges [1.20-Forge-4.0.3]
- Nyf's Spiders [2.1.1]
- Framework [0.6.16]
- Sophisticated Core [0.5.105.485]
- Elytra physics [2.0]
- Even Better Amethyst [1.0.4]
- Drip Sounds [0.3.2]
- Highlighter [1.1.7]
- Citadel [2.4.9]
- FallingTree [4.3.1]
- Ender's Delight [1.0.3]
- Solar Flux Reborn [20.1.3]
- ToolStats [16.0.4]
- Blur (Forge) [3.1.0]
- Make Bubbles Pop [${file.jarVersion}-forge]
- Overflowing Bars [8.0.0]
- FTB Quests [2001.1.7]
- Formations [1.0.2]
- MEGA Cells [2.2.3-1.20.1]
- AmbientSounds [5.3.1]
- Fast Paintings [1.20-1.2.3]
- Corpse [1.20.1-1.0.5]
- VisualOverhaul [5.0.1]
- Open Parties and Claims [0.20.1]
- Leaves Be Gone [8.0.0]
- EnhancedVisuals [1.6.9]
- Gardens of the Dead [4.0.1]
- Biomes O' Plenty [18.0.0.598]
- AE2WTLib [15.1.3-forge]
- Default Options [18.0.1]
- Crabber's Delight [1.1.3]
- Serene Seasons [9.0.0.46]
- YUNG's Better Jungle Temples [1.20-Forge-2.0.4]
- Better Conduit Placement [3.1]
- Nature's Compass [1.20.1-1.11.2-forge]
- Baubley Heart Canisters [1.20.1-1.0.5]
- Canary [0.2.7]
- TrampleNoMore [13.0.2]
- Easy Magic [8.0.1]
- Shield Expansion [1.1.6a]
- GUI Clock [4.3]
- Deeper and Darker [1.2.1]
- Eyes in the Darkness [1.3.10]
- Attack Speed Enchantment [1.3.0.20]
- Additional Structures [4.2.1]
- NotEnoughAnimations Mod [1.6.4]
- Redirector [1.20.1-4.4.0]
- Easy Anvils [8.0.1]
- SparseStructuresReforged [1.19.2-1.20.1-0.0.2]
- AeroBlender [1.20.1-1.0.1-neoforge]
- Simply Steel [1.20.1-2.3.1]
- HammerLib [20.1.23]
- Towns and Towers [1.11.1]
- Just Enough Effects Descriptions [1.20-2.1.6]
- Void Totem [3.0.1]
- Logprot [1.4]
- flib [0.0.11]
- Chipped [3.0.1]
- Euphonium [1.0.1+1.20]
- Decorative Blocks [4.0.2]
- Jade [11.6.3]
- EMI [1.0.24+1.20.1+forge]
- Just Enough Advancements [1.20.1-5.0.1]
- Elevator Mod [1.20.1-lex-1.9]
- Soul fire'd [3.2.0.1-final]
- Prism [1.0.5]
- Second Chance Forge [1.5.1]
- Diagonal Fences [8.1.2]
- Inventory Profiles Next [1.10.9]
- Mob Grinding Utils [1.20.1-1.0.3]
- Bartering Station [8.0.0]
- Eroding Stone Entities [4.3]
- Neruina [1.2.6]
- AnimaticaReforged [1.20.1-0.1.2]
- From The Fog [1.9.2]
- Embeddium [0.2.9+mc1.20.1]
- ModernFix [5.9.3+mc1.20.1]
- Light Overlay [8.0.0]
- Bookshelf [20.1.6]
- Clumps [12.0.0.3]
- YUNG's Better Strongholds [1.20-Forge-4.0.3]
- Falling Leaves [2.1.0]
- Twigs [1.20.1-3.1.0]
- Bountiful [6.0.3+1.20.1]
- Formations Overworld [1.0.1]
- Drippy Loading Screen [2.2.4]
- Recast [3.1]
- Entity Model Features [1.1.0]
- Paxi [1.20-Forge-4.0]
- GroovyModLoader (GML) [4761874]
- Moderately Enough Effect Descriptions [1.0.0]
- Nullscape [1.2.3]
- Universal Bone Meal [8.0.1]
- Better Spawner Control [4.3]
- Ash API [3.0.2+1.20.1]
- Nether's Delight [1.20.1-4.0]
- FullStack Watchdog [1.0.1+1.19.2-forge]
- Hourglass [1.2.1.1]
- Factory API [2.0.1]
- Formations Nether [1.0.2]
- Sound Physics Remastered [1.20.1-1.2.1]
- Boat Item View [0.0.5]
- Structory [1.3.3]
- Xaero's World Map [1.36.0]
- SuperMartijn642's Core Lib [1.1.15]
- ObsidianUI [0.1.2+1.20.1]
- The Aether [1.20.1-1.0.0-beta.1.4-neoforge]
- Let Sleeping Dogs Lie [1.2.0]
- Snow! Real Magic! [9.0.2]
- Balm [7.1.4]
- Tectonic [2.1.1]
- Client Tweaks [11.1.0]
- The Conjurer [1.1.6]
- Mindful Darkness [8.0.2]
- Hopper Bucket [1.0.2]
- YUNG's Better End Island [1.20-Forge-2.0.4]
- Load My F***ing Tags [1.0.3+1.20.1]
- Better Beacon Placement [3.2]
- Supplementaries [1.20-2.6.26]
- Stalwart Dungeons [1.2.8]
- Enchanting Infuser [8.0.2]
- Equipment Compare [1.3.7]
- Boat Break Fix [1.0.2]
- Server Country Flags [1.9.2]
- What Are You Voting For? 2023 [1.2.2]
- TerraBlender [3.0.0.169]
- Farmer's Delight [1.20.1-1.2.3]
- LibX [1.20.1-5.0.8]
- Cristel Lib [1.1.5]
- EnchantmentDescriptions [17.0.8]
- Carry On [2.1.2.5]
- Supplementaries Squared [1.20-1.1.10]
- Twilight's Flavor & Delight [2.0.3]
- EMI Trades [1.2.0+mc1.20.1]
- World Preview [1.1.0]
- Terralith [2.4.8]
- Curios API [5.4.2+1.20.1]
- Villages&Pillages [1.0.0]
- Explorations+ [1.20.1-1.5.2]
- AttributeFix [21.0.3]
- keymap [0.9.0-beta.1+1.20.1-forge]
- WaveyCapes Mod [1.3.2]
- Connectivity Mod [1.20.1-4.6]
- SuperMartijn642's Config Library [1.1.8]
- Voidscape [1.20.1-1.5.295]
- BadMobs [19.0.2]
- BetterF3 [7.0.2]
- Map Atlases [1.20-5.11.0]
- FTB Library [2001.1.4]
- Just Enough Breeding [1.0.10]
- Kotlin for Forge [4778283]
- Moonlight Library [1.20-2.8.61]
- The Twilight Forest [4865711]
- Music Manager [4865923]
- Supplementaries [4865567]
- TexTrue's Embeddium Options [4866426]
- Merchant Markers [Forge] [4769211]
- emi_loot-0.6.5+1.20.1+forge

**Comment by SiverDX** [comment]
might need to post the latest.log here 

or try without nochatreports

**Comment by PlayfulPiano** [comment]
[latest.log](https://github.com/unilock/EMI_loot/files/13358347/latest.log)

**Comment by PlayfulPiano** [comment]
also here it is without ncr
[crash-2023-11-14_19.06.54-client.txt](https://github.com/unilock/EMI_loot/files/13358446/crash-2023-11-14_19.06.54-client.txt)

**Comment by SiverDX** [comment]
[net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'badpackets', Requested by: 'emi_loot', Expected range: '[0.4.0,)', Actual version: '[MISSING]'

**Comment by PlayfulPiano** [comment]
oh, wow yep that was it. Didn't realize that badpackets would be a prereq here. Thanks.
