### ISSUE TITLE
[readme] redundant notes

### ISSUE THREAD

**Issue by ColonelGerdauf** [unilock/EMI_loot#3]
- Better End
- Better Nether
- Paradise Lost

These three mods are specific to Fabric and outside the scope of this port. A few have attempted to port Better End, but that is exclusive to 1.16.5 thus far. Better Nether has been too buggy and hacky in the scope of Forge (and honestly Minecraft modding as a whole) for anyone to bother. And Paradise Lost is the Fabric port of Aether, which is available in 1.19.2, 1.19.4, and 1.20.x.

Does Aether have the compatibility concerns that Paradise Lost has? Not sure. I do not even know if PL is following Aether's footsteps more or less, porting over Aether updates, or are simply going their own path.

**Comment by unilock** [comment]
The README has been left mostly unmodified from upstream. Besides, technically, the port compiles for both Fabric *and* Forge.
