### ISSUE TITLE
Doesn't work on 1.19.2

### ISSUE THREAD

**Issue by vanutp** [unilock/EMI_loot#6]
Forge version: 43.4.2
EMI version: 1.1.9
EMI Loot version: 0.6.6+fix3
No other mods are installed.

When trying to use mod (pressing R/LMB on an item, e.g. a bone), nothing happens.
EMI Loot 0.6.5 works properly
Logs: https://mclo.gs/nihjZAy

**Comment by unilock** [comment]
The mod works after you run `/reload`, so I suspect this is another issue with data sending... sigh. I'll look into it.

**Comment by unilock** [comment]
Fixed by https://github.com/unilock/EMI_loot/commit/ca45472befd19e5f67a3e29cdb68a2363367a9db.

@fzzyhmstrs, could you upload this build to CurseForge / Modrinth? :sweat_smile: (only the 1.19.2 branch needed a fix)  
https://github.com/unilock/EMI_loot/actions/runs/9811067751
